In [1]:
import numpy as np

In [2]:
def binary_encode(i, num_digits):
    return np.array([i >> d & 1 for d in range(num_digits)])

def to_binary(i):
    return np.array([int(s) for s in str(bin(i)[2:]).zfill(8)])

def one_hot(i):
    if i % 15 == 0: return np.array([0, 0, 0, 1])
    if i % 5 == 0: return np.array([0, 0, 1, 0])
    if i % 3 == 0: return np.array([0, 1, 0, 0])
    return np.array([1, 0, 0, 0])
    
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(x, 0)

def softmax(x):
    return np.exp(x) / sum([np.exp(a) for a in range(1, x.shape[1])])

print(to_binary(10))
print(binary_encode(10, 4))
print(one_hot(11))

[0 0 0 0 1 0 1 0]
[0 1 0 1]
[1 0 0 0]


# create training data

In [3]:
trX, trY = [], []

for i in range(1, 99):
    trX.append(to_binary(i))
    trY.append(one_hot(i))
    
trX = np.array(trX)
trY = np.array(trY)

print(trX.shape, trY.shape)

(98, 8) (98, 4)


# Init Weights

In [4]:
wh = 2*np.random.random((8, 98)) - 1
wo = 2*np.random.random((98, 4)) - 1

print(np.dot(trX, wh).shape[0])

98


In [5]:
for i in range(10000):
    hidden_layer = relu(np.dot(trX, wh))
    output_layer = sigmoid(np.dot(hidden_layer, wo))
    
    output_layer_error = trY - output_layer
    if i % 1000 == 0:
        print(np.mean(np.abs(output_layer_error)))
        
    # backpropagation
    output_layer_delta = output_layer_error * (output_layer * (1 - output_layer))
    
    hidder_layer_error = output_layer_delta.dot(wo.T)
    hidden_layer_delta = hidder_layer_error * (hidden_layer * (1 - hidden_layer))
    
    # update weights
    wo += hidden_layer.T.dot(output_layer_delta)
    wh += trX.T.dot(hidden_layer_delta)
    
print(output_layer)

0.6044331713723551
0.22959183672178815


/home/rohankar/.local/lib/python3.5/site-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in exp
  


0.2295918367218806
0.2295918367219725
0.22959183672206387
0.22959183672215472
0.22959183672224504
0.22959183672233485
0.22959183672242414
0.22959183672251293
[[1.00000000e+000 0.00000000e+000 2.22822588e-053 2.08384535e-032]
 [1.00000000e+000 0.00000000e+000 2.43779791e-265 3.03558862e-126]
 [1.00000000e+000 0.00000000e+000 3.55499245e-303 4.82175511e-147]
 [1.00000000e+000 4.81090296e-015 9.53683760e-019 4.24573801e-016]
 [1.00000000e+000 4.98153828e-029 1.49259824e-032 1.69901705e-027]
 [1.00000000e+000 0.00000000e+000 8.05771019e-226 1.83373614e-110]
 [1.00000000e+000 0.00000000e+000 6.91104975e-270 7.71472860e-136]
 [1.00000000e+000 2.27324385e-011 6.93199603e-019 5.45571954e-013]
 [1.00000000e+000 6.38480257e-025 7.33782366e-034 8.49141437e-025]
 [1.00000000e+000 0.00000000e+000 1.00070572e-097 1.40167913e-047]
 [1.00000000e+000 0.00000000e+000 3.81281092e-141 5.02867318e-072]
 [1.00000000e+000 1.22256725e-021 2.69988692e-031 2.53475546e-025]
 [1.00000000e+000 1.92800444e-035 2.74