# Python

## Python read like psudocode, see quick sort example

In [1]:
def quicksort(a):
    if len(a) <= 1:
        return a
    pivot = a[len(a) // 2]
    
    upper = [x for x in a if x < pivot]
    middle = [x for x in a if x == pivot]
    lower = [x for x in a if x > pivot]
    
    return quicksort(upper) + middle + quicksort(middle)

quicksort([3, 62, 23, 64, 1, 34])

[1, 1, 23, 23, 64, 64]

## Sliciing

In [2]:
xs = list(range(5))
print(xs)

print(xs[2:4])
print(xs[2:])
print(xs[:3])
print(xs[:-1])
print(xs[:])

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]


# NumPy

## Initlize numpy array using python list

In [3]:
import numpy as np

a = np.array([1, 2, 3])
print(a.shape)
print(a[1])

a[0]=3
print(a)

b = np.array([[1, 3, 4], [1, 3, 1]])
print(b.shape)
print(b[0, 0])

(3,)
2
[3 2 3]
(2, 3)
1


## some numpy functions to create array

In [4]:
a = np.zeros((2, 2))
print(a)

b = np.ones((2, 3))
print(b)

# create constant array
c = np.full((2, 2), 8)
print(c)

# identity matrix
d = np.eye(2)
print(d)

e = np.random.random((2, 3))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8]
 [8 8]]
[[1. 0.]
 [0. 1.]]
[[0.69490631 0.36480658 0.13441423]
 [0.33390743 0.18536408 0.7175147 ]]


## array indexing - slicing

In [5]:
a = np.random.randint(1, high=10, size=(3, 3))
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2
b = a[:2,:2]
print(b)

# A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0, 0])
b[0][0] = 10
print(a[0][0])

[[1 8 7]
 [1 2 7]
 [5 5 7]]
[[1 8]
 [1 2]]
1
10


we can mix array indexing with slice indexing, but using array indexing results in array of lower rank

In [6]:
a = np.random.randint(1, 10, (4, 4))
print(a)

# 2 ways to acces second row, one using index and second one is using slice
r2_1 = a[1, :]
r2_2 = a[1:2, :]
print(r2_1);print(r2_1.shape) # yeilds array os ower rank
print(r2_2);print(r2_2.shape) # same rank as original array

# same thing happen with column
c2_1 = a[:, 1]
c2_2 = a[:, 1:2]
print(c2_1);print(c2_1.shape)
print(c2_2);print(c2_2.shape)

[[5 8 2 3]
 [1 2 9 6]
 [6 7 7 1]
 [9 4 5 9]]
[1 2 9 6]
(4,)
[[1 2 9 6]]
(1, 4)
[8 2 7 4]
(4,)
[[8]
 [2]
 [7]
 [4]]
(4, 1)


### One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [7]:
a = np.random.randint(1, 10, (3,3))
print(a)

# create array of indices
b = np.array([0, 2, 1])

# select one element from each row using indices in b
print(a[np.arange(3), b])

# mutate each one element from a using index from b
a[np.arange(3), b] += 10
print(a)

[[8 8 2]
 [6 4 9]
 [1 9 2]]
[8 9 9]
[[18  8  2]
 [ 6  4 19]
 [ 1 19  2]]


## Boolean array indexing

### this indexing used to select array elments which satisfy some condition on array

In [8]:
a = np.random.randint(1, 10, (3, 3))
print(a)

# find array elements > 2, this will return boolean array same rank as original array, the True value means
# condition satisy at that index
bool_idx = a > 2
print(bool_idx)

# print rank 1 array consisting elemtns corresponding to the True
print(a[bool_idx])

# one liner
print(a[a > 2])

[[9 2 2]
 [9 1 9]
 [5 2 7]]
[[ True False False]
 [ True False  True]
 [ True False  True]]
[9 9 9 5 7]
[9 9 9 5 7]


# Array Math

In [18]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,2))
print(a);print(b)

print(a+b);print(np.add(a, b))

# element wise multiplication
print()
print(a * b)

# dot product
print()
print(a.dot(b))

print(np.sum(a))

print(a.T)

[[8 7]
 [5 5]]
[[1 4]
 [8 7]]
[[ 9 11]
 [13 12]]
[[ 9 11]
 [13 12]]

[[ 8 28]
 [40 35]]

[[64 81]
 [45 55]]
25
[[8 5]
 [7 5]]


# Broadcast

In [25]:
v = np.array([3, 2, 1])
w = np.array([1, 2])

print(v); print(v.shape)
v = v.reshape(3, 1)
print(v);print(v.shape)

print()
print(w);print(w.shape)

print()
print(v * w)

[3 2 1]
(3,)
[[3]
 [2]
 [1]]
(3, 1)

[1 2]
(2,)

[[3 6]
 [2 4]
 [1 2]]
